### ISSUE TITLE
Editing an existing file inside sarc archive

### ISSUE THREAD

**Issue by mariopossamato** [leoetlino/sarc#3]
Say I have a file inside of a sarc archive; how would I go about changing the data of that file?

**Comment by NiceneNerd** [comment]
With the Python library or with the CLI tool?

**Comment by mariopossamato** [comment]
The Python library

**Comment by NiceneNerd** [comment]
The example in the readme covers everything you would need. Basically, just delete the file and then add the new version back. To slightly modify the sample code:

```python
import sarc

writer = sarc.make_writer_from_sarc(archive)
# or if you're reading from a file
writer = sarc.read_sarc_and_make_writer(file)
# or for a blank archive
writer = sarc.SARCWriter(be=big_endian)

writer.delete_file('test.bfevfl')
writer.add_file('test.bfevfl', b'replacing a file')

writer.write(output_stream)
```

**Comment by mariopossamato** [comment]
Ah, ok.  Thank you! :)

**Comment by mariopossamato** [comment]
One more quick thing:  Is there a way to store the archive's data to a variable without writing it to a file?

**Comment by NiceneNerd** [comment]
You can write it to any filelike object, including [io.BytesIO](https://docs.python.org/3/library/io.html#io.BytesIO)

**Comment by mariopossamato** [comment]
Thanks! :)
